### ISSUE TITLE
Footnote styles

### ISSUE THREAD

**Issue by zuphilip** [rmzelle/ref-extractor#17]
It seems that the extractions for documents with footnote styles is currently not working. Here is an example document in CMOS (full note): [Dok9.docx](https://github.com/rmzelle/ref-extractor/files/1577263/Dok9.docx). The same document works after switched a non-footnote style.

See also https://twitter.com/zuphilip/status/943612742719680513

**Comment by rmzelle** [comment]
@zuphilip, could you give this a try? Should be live already. It turned out that Word stores footnote citations in a separate file within the .docx zip file ("word/footnotes.xml"), so that required some tweaks.

(also, could you test the latest version of ref-extractor with the same document, but with endnotes instead of footnotes? There should be a setting in the Zotero document preferences to switch between the two, https://www.zotero.org/support/word_processor_plugin_usage#document_preferences, but I don't have a copy of Word handy on my dev machine to test this myself. I'm seeing another file, "word/endnotes.xml", so chances are I'll need to extract citations from that too, for endnote citations)

**Comment by zuphilip** [comment]
I tested the document with footnotes as well as another one with footnotes and bibliography. Everthing works fine for them. Thank you!

Here are two documents with endnotes, which are currently not yet working: [Dok9-endnotes.docx](https://github.com/rmzelle/ref-extractor/files/1595115/Dok9-endnotes.docx) , [Dok9-endnotes2.docx](https://github.com/rmzelle/ref-extractor/files/1595117/Dok9-endnotes2.docx) . Let me know if you need more for testing.
